version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: Enterprise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Student_1234
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql  # Mount SQL script
      - ./insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql

    networks:
      - app-network
    ports:
      - "5432:5432"

  web:
    build: ../src
    ports:
#      - "5000:5000"
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DOCKER_CONTAINER: 'true'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
