apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: RW50ZXJwcmlzZQ==  # base64 encoded value of 'Enterprise'
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded value of 'postgres'
  POSTGRES_PASSWORD: U3R1ZGVudF8xMjM0  # base64 encoded value of 'Student_1234'
